# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LAS_SAMPLE_018' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  # Pods for LAS_SAMPLE_018

  target 'LAS_SAMPLE_018Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LAS_SAMPLE_018UITests' do
    # Pods for testing
  end

end
